version: "3.8"
services:
  db:
    container_name: "db"
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=edu_user
      - POSTGRES_PASSWORD=edu_pass
      - POSTGRES_DB=edu_db
    ports:
      - '5432:5432'
    networks:
      - custom

networks:
  custom:
    driver: bridge
